Sidebar mouse actions was not working as expected: Strategy: 1. Moved the following functions to app.component.ts from main.js:     runContainerHeight();     runElementsPosition();     runToggleSideBars();     runClosedBarButton();
Issues from above:
$(...).velocity() is not a function error
solution:
replace $(...).velocity() with $(...).animate()

'ease' animation error
The issue was not resolved by all 'ease' were removed

Error: jQuery.Deferred exception: mainNavigation.perfectScrollbar is not a function
solution: $ npm install perfect-scrollbar:
    const psMainNavigation = new PerfectScrollbar('.main-navigation');
    const psRightWrp = new PerfectScrollbar('.right-wrapper');

    //mainNavigation.perfectScrollbar('update');
    //$('.right-wrapper').perfectScrollbar('update');
    psMainNavigation.update();
    psRightWrp.update();

viewport() function error: has unresolved line:
    e = document.documentElement || document.body;